INSERT INTO COURSE (NAME,CATEGORY,DESCRIPTION) VALUES ('JAVA', 'LANGUAGE', 'JAVA LANGUAGE 11');
INSERT INTO COURSE (NAME,CATEGORY,DESCRIPTION) VALUES ('SPRING', 'FRAMEWORK', 'SPRING FRAMEWORK FOR ENTERPRISE');
INSERT INTO COURSE (NAME,CATEGORY,DESCRIPTION) VALUES ('JEE9', 'FRAMEWORK', 'JAKARTA ENTERPRISE EDITION');

